name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: "Download Depot Tools"
      shell: bash
      run: |
        wget -Odepot_tools.zip https://storage.googleapis.com/chrome-infra/depot_tools.zip
        7z x depot_tools -o"%TEMP%/depot_tools"
    - name: "Configure"
      shell: cmd
      run: |
        SET "PATH=%TEMP%/depot_tools;%PATH%"
        SET "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        SET "GYP_MSVS_VERSION=2017"
        CALL gclient sync
        CALL gn gen out/Debug_x86 --args="rtc_include_tests=false rtc_use_h264=true target_cpu=\"x86\" symbol_level=2 is_debug=true"
        CALL gn gen out/Debug_x64 --args="rtc_include_tests=false rtc_use_h264=true target_cpu=\"x64\" symbol_level=2 is_debug=true"
        CALL gn gen out/Release_x86 --args="rtc_include_tests=false rtc_use_h264=true target_cpu=\"x86\" symbol_level=0 is_debug=false"
        CALL gn gen out/Release_x64 --args="rtc_include_tests=false rtc_use_h264=true target_cpu=\"x86\" symbol_level=0 is_debug=false"
    - name: "Build"
      shell: cmd
      run: |
        SET "PATH=%TEMP%/depot_tools;%PATH%"
        SET "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        SET "GYP_MSVS_VERSION=2017"
        CALL autoninja -C out/Debug_x86 webrtc
        CALL autoninja -C out/Debug_x64 webrtc
        CALL autoninja -C out/Release_x86 webrtc
        CALL autoninja -C out/Release_x64 webrtc

